version: '3.8'

services:
  giavang-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gold-tracker-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=gold_tracker
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FRONTEND_URL=https://gold-tracker-ncr94mia9-nguyenpts-projects.vercel.app
      - COOKIE_DOMAIN=gold-tracker-ncr94mia9-nguyenpts-projects.vercel.app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env.docker:/app/.env
    restart: unless-stopped
    networks:
      - traefik_default
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_default'
      - 'traefik.http.routers.giavang-api.entrypoints=http'
      - 'traefik.http.routers.giavang-api.rule=Host(`giavang-api.trungthanhdev.com`)'
      - 'traefik.http.routers.giavang-api-secure.entrypoints=https'
      - 'traefik.http.routers.giavang-api-secure.rule=Host(`giavang-api.trungthanhdev.com`)'
      - 'traefik.http.routers.giavang-api-secure.tls.certresolver=letsencrypt'


  postgres:
    image: postgres:16-alpine
    container_name: gold-tracker-postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gold_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 
